// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaquetShop.Data;

namespace RaquetShop.Migrations
{
    [DbContext(typeof(RaquetShopDBContext))]
    [Migration("20211210153041_InicialRaquetMigra")]
    partial class InicialRaquetMigra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RaquetShop.Data.Entities.BrandEntity", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("RaquetShop.Data.Entities.RaquetEntity", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("brandId")
                        .HasColumnType("bigint");

                    b.Property<int?>("cantidad")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("peso")
                        .HasColumnType("real");

                    b.Property<int?>("precio")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("Raquets");
                });

            modelBuilder.Entity("RaquetShop.Data.Entities.RaquetEntity", b =>
                {
                    b.HasOne("RaquetShop.Data.Entities.BrandEntity", "Brand")
                        .WithMany("raquets")
                        .HasForeignKey("brandId");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("RaquetShop.Data.Entities.BrandEntity", b =>
                {
                    b.Navigation("raquets");
                });
#pragma warning restore 612, 618
        }
    }
}
